version: "3"

services:
  pihole:
    image: diginc/pi-hole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      ServerIP: "${SERVER_IP}"
    volumes:
      - /srv/pihole/:/etc/pihole/
        # pihole.log has to be created before container comes up
      - /srv/pihole/pihole.log:/var/log/pihole.log
    restart: unless-stopped

